/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.megatim.common.clients;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.table.TableRowSorter;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

import com.bekosoftware.genericdaolayer.dao.tools.RestrictionsContainer;
import com.bekosoftware.genericmanagerlayer.core.ifaces.GenericManager;
import com.megatim.common.annotationsprocessor.ValidateAndFillBeans;
import com.megatim.common.utilities.MessagesBundle;
import com.megatim.common.utilities.TypeOperation;
import com.megatim.security.enumerations.EnumStatutAutorisation;
import com.megatim.security.model.Autorisation;

import java.io.File;

import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author DEV_4
 * @param <T>
 * @param <PK>
 */
public abstract class AbstractListTransfertTemplateFrame<T extends Object, U extends Object, PK extends Serializable>
        extends javax.swing.JInternalFrame implements MouseListener, KeyListener {

    /**
     * Creates new form AbstractListTemplateFrame
     */
    public AbstractListTransfertTemplateFrame() {
        super(" ", true, false, true);
        bundle = ResourceBundle.getBundle("messages");
        initComponents();
        buildViewComponents();
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        //buildViewComponents();
        this.setResizable(true);
        this.setClosable(true);
        this.addKeyListener(this);
        securisationFrame();
    }

     /**
     * Applique les r_gles de sécurité a la fenetre 
     * courante
     */
    private void securisationFrame(){
        
        if(getAutorisation()!=null){
            if(EnumStatutAutorisation.READ.equals(getAutorisation().getStatut())){
                btvalider.setEnabled(false);
                btunusebutton_1.setEnabled(false);
                //btde.setEnabled(false);
                //btdelete.setEnabled(false);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        bannierePanel = new javax.swing.JPanel();
        seachactionsPanel = new javax.swing.JPanel();
        btsearch = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        actionsPanel = new javax.swing.JPanel();
        btvalider = new javax.swing.JButton();
        btprint = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        btconsulter = new javax.swing.JButton();
        btunusebutton_1 = new javax.swing.JButton();
        datasPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        javax.swing.GroupLayout bannierePanelLayout = new javax.swing.GroupLayout(bannierePanel);
        bannierePanel.setLayout(bannierePanelLayout);
        bannierePanelLayout.setHorizontalGroup(
            bannierePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bannierePanelLayout.setVerticalGroup(
            bannierePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        seachactionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btsearch.setText("Rechercher");
        btsearch.setIcon(getSeachIcon());
        btsearch.setText(getSeachTitle());
        btsearch.setToolTipText(getSearchTooltip());
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        btreset.setText("Effacer");
        btreset.setIcon(getClearIcon());
        btreset.setText(getClearTitle());
        btreset.setToolTipText(getClearTooltip());
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seachactionsPanelLayout = new javax.swing.GroupLayout(seachactionsPanel);
        seachactionsPanel.setLayout(seachactionsPanelLayout);
        seachactionsPanelLayout.setHorizontalGroup(
            seachactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        seachactionsPanelLayout.setVerticalGroup(
            seachactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seachactionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btreset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        seachactionsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btreset, btsearch});

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bannierePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seachactionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(bannierePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seachactionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        actionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        btvalider.setText("Valider");
        btvalider.setIcon(getNewIcon());
        btvalider.setText(getNewTitle());
        btvalider.setToolTipText(getNewTooltip());
        btvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvaliderActionPerformed(evt);
            }
        });

        btprint.setText("Imprimer");
        btprint.setIcon(getPrintIcon());
        btprint.setText(getPrintTitle());
        btprint.setToolTipText(getPrintTooltip());
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });

        btcancel.setText("Quitter");
        btcancel.setIcon(getCancelIcon());
        btcancel.setText(getCancelTitle());
        btcancel.setToolTipText(getCancelTooltip());
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        btconsulter.setText("Consulter");
        btconsulter.setIcon(getViewIcon());
        btconsulter.setText(getViewTitle());
        btconsulter.setToolTipText(getViewTooltip());
        btconsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconsulterActionPerformed(evt);
            }
        });

        btunusebutton_1.setText("To Customize");
        btunusebutton_1.setVisible(false);

        javax.swing.GroupLayout actionsPanelLayout = new javax.swing.GroupLayout(actionsPanel);
        actionsPanel.setLayout(actionsPanelLayout);
        actionsPanelLayout.setHorizontalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btconsulter, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btunusebutton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        actionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btcancel, btconsulter, btprint, btunusebutton_1, btvalider});

        actionsPanelLayout.setVerticalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btunusebutton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btconsulter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        actionsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btcancel, btconsulter, btprint, btunusebutton_1, btvalider});

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout datasPanelLayout = new javax.swing.GroupLayout(datasPanel);
        datasPanel.setLayout(datasPanelLayout);
        datasPanelLayout.setHorizontalGroup(
            datasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
            .addGroup(datasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datasPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)))
        );
        datasPanelLayout.setVerticalGroup(
            datasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(datasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(datasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        try {
            // TODO add your handling code here:
            if (getPagination() != null) {
                getPagination().setSize(count());
            }
            search();
        } catch (Exception ex) {
            Messages.Messages(getApplicationFrame(), true, NotificationType.ERROR, "Erreur lors du traitement\nVeuillez consulter les détails", ex.getMessage(), "");
            Logger.getLogger(AbstractListTransfertTemplateFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btsearchActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btresetActionPerformed

    private void btvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvaliderActionPerformed
        try {
            // TODO add your handling code here:
            valider();
        } catch (Exception ex) {
            Messages.Messages(getApplicationFrame(), true, NotificationType.ERROR, "Erreur lors du traitement\nVeuillez consulter les détails", ex.getMessage(), "");
            Logger.getLogger(AbstractListTransfertTemplateFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btvaliderActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
        try {
            // TODO add your handling code here:
            imprimer();
        } catch (Exception ex) {
            Messages.Messages(getApplicationFrame(), true, NotificationType.ERROR, "Erreur lors du traitement\nVeuillez consulter les détails", ex.getMessage(), "");
            Logger.getLogger(AbstractListTransfertTemplateFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btprintActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    private void btconsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconsulterActionPerformed
        try {
            // TODO add your handling code here:
            consulter();
        } catch (Exception ex) {
            Messages.Messages(getApplicationFrame(), true, NotificationType.ERROR, "Erreur lors du traitement\nVeuillez consulter les détails", ex.getMessage(), "");
            Logger.getLogger(AbstractListTransfertTemplateFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btconsulterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JPanel bannierePanel;
    protected javax.swing.JButton btcancel;
    protected javax.swing.JButton btconsulter;
    protected javax.swing.JButton btprint;
    private javax.swing.JButton btreset;
    private javax.swing.JButton btsearch;
    protected javax.swing.JButton btunusebutton_1;
    protected javax.swing.JButton btvalider;
    protected javax.swing.JTable dataTable;
    private javax.swing.JPanel datasPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel seachactionsPanel;
    // End of variables declaration//GEN-END:variables

    protected JPanel criteriaPanel = null;

    protected AbstractTableBaseListModel model = null;

    protected AbstractTableBaseListModel modelValidation = null;

    protected PaginationStep pagination = null;

    protected ResourceBundle bundle = null;
    /**
     * Current
     */
    protected T currentObject;

    protected TypeOperation typeOperation = TypeOperation.NEW;

    /**
     * ******************************************************************************************************
     */
    /**
     *
     *********************************************************************************************************
     */
    /**
     * Construction de l'interface graphique
     */
    public void buildViewComponents() {
        //Construction de la banniere
        buildBanniere();
        buildFooterPanel();
        buildCriteriaPanel();
        RowSorter sorter = new TableRowSorter(getTableModel());
        dataTable.setRowSorter(sorter);
        dataTable.setModel(getTableModel());
        dataTable.addMouseListener(this);
        this.setResizable(false);
        this.setClosable(true);
        search();
    }

    /**
     * Construction de la banniere de l'application
     */
    public void buildBanniere() {
        JLabel lblIcon = new javax.swing.JLabel();
        JLabel lblTitle = new javax.swing.JLabel();
        //Intitialisation logo
        ImageIcon icon = CommonsUtilities.getIcone();
        this.setFrameIcon(new ImageIcon(icon.getImage()));
        this.setTitle(getTitle());
        //traitement du panel Header
        bannierePanel.setLayout(new BorderLayout());
        if (getTitreHeaderPanel() != null) {
            JPanel entetePanel = getTitreHeaderPanel();
            lblIcon.setIcon(getImage());
            entetePanel.add(lblIcon);
            lblTitle.setFont(CommonsUtilities.getFontTitreFrame());
            lblTitle.setForeground(CommonsUtilities.COULEUR_TITRE_FRAME);
            lblTitle.setText(getWindowTitle());
            lblTitle.setName("lblTitle"); // NOI18N
            entetePanel.add(lblTitle);
            bannierePanel.add(entetePanel, BorderLayout.CENTER);
        }
    }

    public void buildCriteriaPanel() {

        filterPanel.setLayout(new BorderLayout());
        if (getCriteriaPanel() != null) {
            filterPanel.add(getCriteriaPanel(), BorderLayout.CENTER);
        }
    }

    public void buildFooterPanel() {
        filterPanel.setLayout(new BorderLayout());
        if (getFooterPanel() != null) {
            filterPanel.add(getFooterPanel(), BorderLayout.CENTER);
        }
    }

    /**
     * Recupere les valeurs et construit des objects
     *
     * @throws IllegalAccessException
     */
    public void collecteCurrentObjectData() throws IllegalAccessException {

        if (getCriteriaPanel() == null) {
            return;
        }
        //Validation et transfert du contenu
        if (ValidateAndFillBeans.validateBean(getCriteriaPanel())) {
            currentObject = ValidateAndFillBeans.fillBean(getCriteriaPanel(), currentObject);
        }

    }

    /**
     *
     * @return
     */
    protected ImageIcon getSeachIcon() {

        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_search.png"));
    }

    /**
     *
     * @return
     */
    protected String getSeachTitle() {

        return MessagesBundle.getMessage("search.title");
    }

    /**
     *
     * @return
     */
    protected String getSearchTooltip() {
        return MessagesBundle.getMessage("search.tooltip");
    }

    /**
     *
     * @return
     */
    protected ImageIcon getClearIcon() {

        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_clear.png"));
    }

    /**
     *
     * @return
     */
    protected String getClearTitle() {
        return MessagesBundle.getMessage("clear.title");
    }

    /**
     *
     * @return
     */
    protected String getClearTooltip() {
        return MessagesBundle.getMessage("clear.tooltip");
    }

    /**
     *
     * @return
     */
    protected ImageIcon getNewIcon() {

        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_add.png"));
    }

    /**
     *
     * @return
     */
    protected String getNewTitle() {
        return MessagesBundle.getMessage("validate.title");
    }

    /**
     *
     * @return
     */
    protected String getNewTooltip() {
        return MessagesBundle.getMessage("validate.tooltip");
    }

    /**
     *
     * @return
     */
    protected ImageIcon getUpdateIcon() {
        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_edit.png"));
    }

    /**
     *
     * @return
     */
    protected String getUpdateTitle() {
        return MessagesBundle.getMessage("reject.title");
    }

    /**
     *
     * @return
     */
    protected String getUpdateTooltip() {
        return MessagesBundle.getMessage("reject.tooltip");
    }

    /**
     *
     * @return
     */
    protected ImageIcon getDeleteIcon() {
        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_delete.png"));
    }

    /**
     *
     * @return
     */
    protected String getDeleteTitle() {
        return MessagesBundle.getMessage("delete.title");
    }

    /**
     *
     * @return
     */
    protected String getDeleteTooltip() {
        return MessagesBundle.getMessage("delete.tooltip");
    }

    /**
     *
     * @return
     */
    protected ImageIcon getViewIcon() {
        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_display.png"));
    }

    /**
     *
     * @return
     */
    protected String getViewTitle() {
        return MessagesBundle.getMessage("view.title");
    }

    /**
     *
     * @return
     */
    protected String getViewTooltip() {
        return MessagesBundle.getMessage("view.tooltip");
    }

    /**
     *
     * @return
     */
    protected ImageIcon getPrintIcon() {
        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_printer.png"));
    }

    /**
     *
     * @return
     */
    protected String getPrintTitle() {
        return MessagesBundle.getMessage("print.title");
    }

    /**
     *
     * @return
     */
    protected String getPrintTooltip() {
        return MessagesBundle.getMessage("print.tooltip");
    }

    protected ImageIcon getCancelIcon() {
        return new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_cancel.png"));
    }

    protected String getCancelTitle() {
        return MessagesBundle.getMessage("cancel.title");
    }

    /**
     *
     * @return
     */
    protected String getCancelTooltip() {
        return MessagesBundle.getMessage("cancel.tooltip");
    }

    /**
     * Reinitialisation des champs
     *
     * @throws IllegalArgumentException
     * @throws IllegalAccessException
     */
    public void reset() {

        try {
            if (getCriteriaPanel() != null) {
                ValidateAndFillBeans.cleanBeanField(getCriteriaPanel());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     *
     * @return
     */
    public T getCurrentObject() {
        return currentObject;
    }

    /**
     *
     * @param currentObject
     * @throws IllegalAccessException
     * @throws IllegalArgumentException
     */
    public void setCurrentObject(T currentObject) throws IllegalArgumentException, IllegalAccessException {
        this.currentObject = currentObject;

        boolean status = beforeSetCurrentObject();

        if (!status) {
            return;
        }

        if (getCriteriaPanel() == null) {
            return;
        }

        if (currentObject != null && getCriteriaPanel() != null) {
            ValidateAndFillBeans.fillViewBean(currentObject, getCriteriaPanel());
        }

        if (typeOperation == TypeOperation.UPDATE) {
            ValidateAndFillBeans.updatableAnnotationProcessor(getCriteriaPanel());
        } else if (typeOperation == TypeOperation.VIEW) {
            ValidateAndFillBeans.disableAllFields(getCriteriaPanel());
        }

        //Action apres mise a jour
        afterSetCurrentObject();
    }

    /**
     *
     * @throws IllegalArgumentException
     * @throws IllegalAccessException
     */
    public void search() {

        try {
            //Non nullité des criteres
            if (getCriteriaPanel() == null) {
                return;
            }
            //non nulitte du manager
            if (getManager() == null) {
                return;
            }
            //Validite des valeurs des critères
            if (!ValidateAndFillBeans.validateBean(getCriteriaPanel())) {
                return;
            }
            //Constructeur de contenaur de prédicats
            RestrictionsContainer container = ValidateAndFillBeans.buildSearchCriteria(getCriteriaPanel());
            //
            List<T> resultats = new ArrayList<T>();

            resultats = getManager().filter(container.getPredicats(), ValidateAndFillBeans.getOrdersCriteria(), null, 0, -1);
            //System.out.println("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::::::::::::::::::::::::::::::::::"+resultats);
            //Raffraichissement des données
            refresh(resultats);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     *
     * @return @throws IllegalArgumentException
     * @throws IllegalAccessException
     */
    public long count() throws Exception {

        //Non nullité des criteres
        if (getCriteriaPanel() == null) {
            return 0;
        }
        //non nulitte du manager
        if (getManager() == null) {
            return 0;
        }
        //Validite des valeurs des critères
        if (!ValidateAndFillBeans.validateBean(getCriteriaPanel())) {
            return 0;
        }
        //Constructeur de contenaur de prédicats
        RestrictionsContainer container = ValidateAndFillBeans.buildSearchCriteria(getCriteriaPanel());
        //
        List<T> resultats = new ArrayList<T>();

        resultats = getManager().filter(container.getPredicats(), ValidateAndFillBeans.getOrdersCriteria(), null, 0, -1);

        return resultats.size();
    }

    /**
     * Raffraichissement de la fenêtre
     *
     * @param datas
     */
    protected void refresh(List<T> datas) {

        //Verification de la consistence des données
        if (datas == null) {
            datas = new ArrayList<T>();
        }
        //Initialisation du model
        model = getTableModel();
        //Mise a jour de la table
        model.setElements(datas);
        //mise a jour de la table
        dataTable.setModel(model);

    }

    /**
     * Panel des opérations contenant les données de cette fenêtre
     *
     * @return
     */
    protected abstract JPanel getCriteriaPanel();

    /**
     * Obtention de l'identification de l'entité
     *
     * @param Object
     * @return
     */
    protected abstract PK getPrimaryKey(T Object);

    /**
     * Classe responsable de la mise a disposition du manager
     *
     * @return
     */
    protected abstract GenericManager getManager() throws Exception;

    /**
     *
     * @return @throws Exception
     */
    protected abstract GenericManager getValideManager() throws Exception;

    /**
     * Gestion de la pagination
     *
     * @return
     */
    protected abstract PaginationStep getPagination();

    /**
     * Return la valeur de la colonne boolean
     *
     * @param objet
     * @return
     */
    protected abstract boolean isSelected(T objet);

    /**
     * Listes des elements selectionnés dans le tableau
     *
     * @return
     */
    protected List<T> getSelectedObjects() {

        boolean updatable = true, deletable = true;
        //Recuperation de la liste des lignes selectionnés
        int[] selectedRows = dataTable.getSelectedRows();

        if (selectedRows == null || selectedRows.length <= 0) {
            return null;
        }

        List<T> datas = model.getElements(selectedRows);

        for (T data : datas) {

            updatable &= updatable(data);
            deletable &= deletable(data);
        }
     //btmodifier.setEnabled(updatable);

        //btsupprimer.setEnabled(deletable);
        return datas;
    }

    /**
     * Selection de la liste des lignes selectionnées
     *
     * @return
     */
    protected List<T> getSelectedRows() {

        List<T> datas = model.getElements();

        List<T> values = new ArrayList<T>();

        for (T data : datas) {

            if (isSelected(data)) {
                values.add(data);
            }
        }

        return values;
    }

    /**
     * i
     * Classe responsable de l'edition du manager
     */
    public void valider() throws Exception {

        List<T> datas = getSelectedRows();

        if (datas == null || datas.isEmpty()) {
            Messages.Messages(getApplicationFrame(), true, NotificationType.INFOS, "Aucun élément n'est sélectionné.", "", "");
            return;
        }

        JDialog dialog = getValideEditDialog(null, getValideManager(), TypeOperation.NEW, getApplicationFrame());
        ((AbstractTransfertTemplateDialog) dialog).setModel(getValidateTableModel());
        dialog.setLocationRelativeTo(getApplicationFrame());
        dialog.setVisible(true);
        search();

    }

    /**
     * Convertion des object de type T en object de type U
     *
     * @param datas
     * @return
     */
    protected List<U> translate(List<T> datas) {

        List<U> values = new ArrayList<U>();

        for (T data : datas) {
            values.add(validateWapper(data));
        }
        return values;
    }

    /**
     * Consultation
     */
    public void consulter() throws Exception {

        if (getSelectedObjects() == null) {
            Messages.Messages(getApplicationFrame(), true, NotificationType.INFOS, "Aucun élément n'est sélectionné.", "", "");
            return;
        }
        //Une ligne est selectionnée
        JDialog nouveauFrame = getEditDialog(getSelectedObjects().get(0), getManager(), TypeOperation.VIEW, getApplicationFrame());
        nouveauFrame.setLocationRelativeTo(getApplicationFrame());
        nouveauFrame.setVisible(true);
    }

    /**
     *
     * @throws JRException
     */
    public void imprimer() throws Exception {

        if (model == null || model.getElements() == null || model.getElements().isEmpty()) {
            return;
        }

        List<T> datas = new ArrayList<T>();
        //Aucun ligne selectionné
        if (getSelectedObjects() == null) {

            datas = model.getElements();
        } else {
            datas = getSelectedObjects();
        }
        String reportFilePath = getJasperFileName();
        // Si le fichier ne se termine pas par .jasper
        if (!reportFilePath.endsWith(".jasper")) {
            reportFilePath = reportFilePath + ".jasper";
        }

        // Creation d'un File sur le fichier
        File reportFile = new File(reportFilePath);
//        System.out.println("le nom du fichier jasper a afficher :" + reportFile);
        // Si l'objet n'existe pas
        if (!reportFile.exists()) {
            throw new RuntimeException("gepa.report.helper.buildreport.reportfile.notexist");
        }

        // Si l'objet n'est pas un fichier
        if (!reportFile.isFile()) {
            throw new RuntimeException("gepa.report.helper.buildreport.reportfile.notexist");
        }

        // Chargement du Rapport
        JasperReport report = null;

        // Etat rempli
        JasperPrint jasperPrint = null;

        // Chargement du report
        report = (JasperReport) JRLoader.loadObject(reportFile);
        jasperPrint = JasperFillManager.fillReport(report, this.getReportParameters(), new JRBeanCollectionDataSource(datas, false));

        // Presentation de l'etat
        this.showReport(jasperPrint);
    }

    /**
     * Fenêtre principale de l'application
     *
     * @return
     */
    protected abstract JFrame getApplicationFrame();

    /**
     * nom de l'action permettant l'appel de cette fenêtre
     *
     * @return
     */
    protected abstract String getActionName();

    /**
     * Entete de page
     *
     * @return
     */
    protected JPanel getHeaderPanel() {
        return CommonsUtilities.headerPanel();
    }

    protected JPanel getTitreHeaderPanel() {
        return CommonsUtilities.titreHeaderPanel();
    }

    /**
     * Pied de page
     *
     * @return
     */
    protected JPanel getFooterPanel() {

        return CommonsUtilities.footerPanel();
    }

    /**
     * Titre de la fênete
     *
     * @return
     */
    protected abstract String getWindowTitle();

    /**
     * Model de la table
     *
     * @return
     */
    public abstract AbstractTableBaseListModel getTableModel();

    /**
     * Model de la table
     *
     * @return
     */
    public abstract AbstractTableBaseListModel getValidateTableModel();

    /**
     * Nom de la classe implementant l'interface
     *
     * @return
     */
    public abstract String getWindowClassName();

    /**
     * Icon de la fênetre
     *
     * @return
     */
    protected abstract ImageIcon getImage();

    /**
     * Parametres des raport
     *
     * @return
     */
    protected abstract Map getReportParameters();

    /**
     * Nom du fichier
     *
     * @return
     */
    protected abstract String getJasperFileName();

    /**
     * Fenetre interne d'edition pour
     *
     * @param object
     * @param manager
     * @param typeOperation
     * @param window
     * @return
     * @throws java.lang.Exception
     */
    protected abstract JDialog getEditDialog(T object, GenericManager manager, TypeOperation typeOperation, JFrame window) throws Exception;

    /**
     *
     * @param object
     * @param manager
     * @param typeOperation
     * @param window
     * @return
     * @throws Exception
     */
    protected abstract JDialog getValideEditDialog(U object, GenericManager manager, TypeOperation typeOperation, JFrame window) throws Exception;

    /**
     *
     * @param object
     * @return
     */
    protected abstract U validateWapper(T object);

    /**
     *
     * @param currentObject
     * @return
     */
    protected boolean updatable(T currentObject) {
        return true;
    }

    /**
     *
     * @param currentObject
     * @return
     */
    protected boolean deletable(T currentObject) {
        return true;
    }

    /**
     *
     * @param object
     * @param manager
     * @param typeOperation
     * @param window
     * @return
     */
    //public abstract JInternalFrame getEditInternalFrame(T object , GenericManager manager , TypeOperation typeOperation , JFrame window);
    /**
     *
     * @return
     */
    protected boolean beforeDelete() {
        return true;
    }

    /**
     *
     * @return
     */
    protected boolean afterDelete() {
        return true;
    }

    /**
     * Actions avant la mise a jour du currrentObject
     *
     * @param currentObject
     * @return
     */
    protected boolean beforeSetCurrentObject() {
        return true;
    }

    /**
     * Actions apres mise a jour du currentObject
     *
     * @return
     */
    protected boolean afterSetCurrentObject() {
        return true;
    }

    /**
     * Verificateur de la précondition avant sauvegarde
     *
     * @return
     */
    protected boolean beforeSave() {
        return true;
    }

    /**
     * Verification postcondition avant sauvegarde
     *
     * @return
     */
    public boolean afterSave() {
        return true;
    }

    /**
     *
     * @return
     */
    public JTable getDataTable() {
        return dataTable;
    }

    @SuppressWarnings("empty-statement")
    public void mouseExited(MouseEvent e) {;
    }

    @SuppressWarnings("empty-statement")
    public void mouseEntered(MouseEvent e) {;
    }

    @SuppressWarnings("empty-statement")
    public void mouseReleased(MouseEvent e) {
        ;
    }

    @SuppressWarnings("empty-statement")
    public void mousePressed(MouseEvent e) {;
    }

    @SuppressWarnings("empty-statement")
    public void mouseClicked(MouseEvent e) {;
    }

    /**
     *
     * @param e
     */
    public void keyReleased(KeyEvent e) {

        if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }

    /**
     *
     * @param e
     */
    @SuppressWarnings("empty-statement")
    public void keyPressed(KeyEvent e) {;
    }

    /**
     *
     * @param e
     */
    @SuppressWarnings("empty-statement")
    public void keyTyped(KeyEvent e) {;
    }

    protected void showReport(JasperPrint jasperPrint) throws Exception {

        // Si le fichier jasper est null, arret
        if (jasperPrint == null) {
            return;
        }

        // Creation du viewer
        JRViewer jrViewer = new JRViewer(jasperPrint);

        // Creation de la boite de dilogue
        JDialog dialog = new JDialog(getApplicationFrame());

        // Injection du viewer dans la boite de dialogue
        dialog.getContentPane().add(jrViewer);

        // Gestion de la fermeture de la boite
        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Titre de la boite
        dialog.setTitle("Etat");

        // set modal a true
        dialog.setModal(true);
        // Dimension de la boite
        dialog.setSize(1300, 700);

        //dialog.pack();  
        // Centrage de la boite sur l'IHM
        dialog.setLocationRelativeTo(getApplicationFrame());
        dialog.setVisible(true);

    }
    
     /**
     * Renvoi le niveau d'autorisation de l'utilisateur courant
     * @return 
     */
    protected  Autorisation getAutorisation(){        
        return null; 
    }
}
