/*                                         
 * To change this license header, choose License Headers in Project Properties.                                        
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.megatim.common.clients;

import com.bekosoftware.genericmanagerlayer.core.ifaces.GenericManager;
import com.megatim.common.annotationsprocessor.AnnotationsProcessor;
import com.megatim.common.annotationsprocessor.ValidateAndFillBeans;
import com.megatim.common.context.ToolsContext;
import com.megatim.common.logger.CustomLogger;
import com.megatim.common.utilities.MessagesBundle;
import com.megatim.common.utilities.PrincipalFrame;
import com.megatim.common.utilities.TypeOperation;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;

import org.apache.log4j.Level;

/**
 *
 * @author DEV
 */
public abstract class AbstractEditTemplateDialog<T extends Object, PK extends Serializable>
        extends javax.swing.JDialog implements KeyListener {

    /**
     *
     * @param parent
     * @param modal
     * @param type
     */
    public AbstractEditTemplateDialog(JFrame parent, boolean modal, TypeOperation type) {
        super(parent, modal);
        this.typeOperation = type;
        initComponents();
        buildViewComponents();
        this.addKeyListener(this);

    }

    /**
     *
     * @param owner
     */
    public AbstractEditTemplateDialog(Frame owner) {
        super(owner);
        buildViewComponents();
        this.addKeyListener(this);
    }

    /**
     *
     * @param owner
     * @param title
     */
    public AbstractEditTemplateDialog(Frame owner, String title) {
        super(owner, title);
        buildViewComponents();
        this.addKeyListener(this);
    }

    /**
     *
     */
    public AbstractEditTemplateDialog() {

        this.setModal(true);
        initComponents();
        buildViewComponents();
        this.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btcancel = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        btnotuse_1 = new javax.swing.JButton();
        btnotuse_2 = new javax.swing.JButton();
        btnotuse_3 = new javax.swing.JButton();
        btnotuse_4 = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        setPreferredSize(new java.awt.Dimension(645, 407));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        btcancel.setText("Quitter");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        btsave.setText("Enregistrer");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        btnotuse_1.setText("To Customize");
        btnotuse_1.setVisible(false);
        
        btnotuse_2.setText("To Customize");
        btnotuse_2.setVisible(false);
        
        
        btnotuse_3.setText("To Customize");
        btnotuse_3.setVisible(false);
        
        btnotuse_4.setText("To Customize");
        btnotuse_4.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnotuse_4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnotuse_3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnotuse_1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnotuse_2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnotuse_4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnotuse_3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnotuse_1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnotuse_2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btcancel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_btsaveActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        quitter();
    }//GEN-LAST:event_btcancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btcancel;
    protected javax.swing.JButton btsave;
    protected javax.swing.JButton btnotuse_1;
    protected javax.swing.JButton btnotuse_2;
    protected javax.swing.JButton btnotuse_3;
    protected javax.swing.JButton btnotuse_4;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    // End of variables declaration                   
    protected javax.swing.JPanel middlePanel;
    protected AbstractListTemplateFrame parentFrame;
    protected T currentObject = null;
    protected GenericManager manager = null;
    protected TypeOperation typeOperation = TypeOperation.NEW;
    protected boolean interne = Boolean.FALSE;
    protected AbstractTableBaseListModel model = null;
    protected AbstractTreeBaseListModel treeModel = null;
    protected int selectedRow = -1;

    /**
     * ******************************************************************************************************
     */
    /**
     *
     *********************************************************************************************************
     */
    /**
     * Construction de l'interface graphique
     */
    public void buildViewComponents() {
        //Construction de la banniere
        buildBanniere();

        centerPanel.setLayout(new BorderLayout());
        middlePanel = getFiledsPanel();
        centerPanel.add(middlePanel, BorderLayout.CENTER);
        if (typeOperation == TypeOperation.VIEW) {
            btsave.setEnabled(false);
            btsave.setVisible(false);
        }
      
        btsave.setText(getSaveTitle());
        btsave.setToolTipText(getSaveTooltip());
        btsave.setIcon(getSaveIcon());
        btcancel.setText(getCancelTitle());
        btcancel.setToolTipText(getCancelTooltip());
        btcancel.setIcon(getCancelIcon());
    }

    /**
     * Construction de la banniere de l'application
     */
    public void buildBanniere() {
        JLabel lblIcon = new javax.swing.JLabel();
        JLabel lblTitle = new javax.swing.JLabel();
        //Intitialisation logo
        this.setIconImage(getIconePage().getImage());
        this.setTitle(getTitle());
        //traitement du panel Header
        headerPanel.setLayout(new BorderLayout());
        if (getHeaderPanel() != null) {
            JPanel entetePanel = getTireHeaderPanel();
            lblIcon.setIcon(getImage());
            entetePanel.add(lblIcon);
            lblTitle.setFont(CommonsUtilities.getFontTitreFrame());
            lblTitle.setForeground(CommonsUtilities.COULEUR_TITRE_FRAME);
            lblTitle.setText(getWindowTitle());
            lblTitle.setName("lblTitle"); // NOI18N
            entetePanel.add(lblTitle);
            if (entetePanel != null) {
                headerPanel.add(entetePanel, BorderLayout.CENTER);
            }
        }
    }

    /**
     * Recupere les valeurs et construit des objects
     *
     * @throws IllegalAccessException
     */
    public void collecteCurrentObjectData() throws IllegalAccessException {
        if (getFiledsPanel() == null) {
            return;
        }
        //Validation et transfert du contenu
        if (ValidateAndFillBeans.validateBean(getFiledsPanel())) {
            currentObject = ValidateAndFillBeans.fillBean(getFiledsPanel(), currentObject);
        }
        //System.out.println("Current Usr Account :::::: "+currentObject);
    }

    /**
     *
     */
    public void save() {

        try {
            //Initialisation des champs du currentOject
            collecteCurrentObjectData();
            //Verification si il ya une entite
            if (currentObject == null) {
                return;
            }
            //Verification de l'existance d'un manager
            if (getManager() == null && model == null) {
                return;
            }

            //Verification de la prÃ©condition		
            boolean precondition = beforeSave();

            if (!precondition) {
                return;
            }

            if (getPrimaryKey(currentObject) == null) {
                CustomLogger.loggerWriteError(getClass(), "save()", MessagesBundle.getMessage("new.entity.id.null"));
                Notification.getNotificationDialog(getApplicationFrame(), true, NotificationType.ERROR, "Erreur pendant  le traitement\nVeuillez consulter les détails", "L'identifiant ne peut être null");
            }

            //Sauvegarde de currentObject 
            if (typeOperation == TypeOperation.NEW) {
                //Test d'existance
                if (!interne && getManager().find(AnnotationsProcessor.getPrimaryKeyName(currentObject.getClass()), getPrimaryKey(currentObject)) != null) {
                    CustomLogger.loggerWriteError(getClass(), "nouveau()", MessagesBundle.getMessage("new.entity.error"));
                    Notification.getNotificationDialog(getApplicationFrame(), true, NotificationType.ERROR, "Duplicate key entry", "Un enregistrement de même cle existe déja");
                    return;
                }
                //Traitement de notre enregistrement
                if (!interne) {
                    getManager().save(currentObject);
                } else {
                    //System.out.println("AbstractEditTemplateDialog.save() :::::::::::::::::::::::::::::::::::: "+currentObject+"  :::::::::::::::::::::::::::::::: "+model.exist((Comparable) currentObject)+" ::::::: "+model.getElements());
                    if (!model.exist((Comparable) currentObject)) {
                        model.addElement((Comparable) currentObject);
                    } else {
                        CustomLogger.loggerWriteError(getClass(), "nouveau()", MessagesBundle.getMessage("new.entity.error"));
                        Notification.getNotificationDialog(getApplicationFrame(), true, NotificationType.ERROR, "Duplicate key entry", "Un enregistrement de même clé existe déja");
                        return;
                    }//if(!model.getElements().contains(currentObject)){
                }
            } else if (typeOperation == TypeOperation.UPDATE) {
                if (!interne) {
                    getManager().update(getPrimaryKey(currentObject), currentObject);
                } else {
                    model.updateElement(selectedRow, (Comparable) currentObject);
                }
            }
            //Validation de la post condition
            afterSave();
            //Mise a jour de la fenÃªtre parent si elle existe
            if (getParentFrame() != null) {
                getParentFrame().search();
            }
            this.dispose();
        } catch (Exception ex) {ex.printStackTrace();
            CustomLogger.loggerWriteError(getClass(), "nouveau()", MessagesBundle.getMessage("new.entity.error"));
            Notification.getNotificationDialog(getApplicationFrame(), true, NotificationType.ERROR, "Erreur pendant  le traitement\nVeuillez consulter les détails", ex.getMessage());

        }
    }

    /**
     *
     * @return
     */
    public T getCurrentObject() {
        return currentObject;
    }

    /**
     *
     * @param currentObject
     * @throws IllegalAccessException
     * @throws IllegalArgumentException
     */
    public void setCurrentObject(T currentObject) throws IllegalArgumentException, IllegalAccessException {
        this.currentObject = currentObject;

        boolean status = beforeSetCurrentObject();

        if (!status) {
            return;
        }

        if (getFiledsPanel() == null) {
            return;
        }

        if (currentObject != null && getFiledsPanel() != null) {
            ValidateAndFillBeans.fillViewBean(currentObject, getFiledsPanel());
        }

        if (typeOperation == TypeOperation.UPDATE) {
            ValidateAndFillBeans.updatableAnnotationProcessor(getFiledsPanel());
        } else if (typeOperation == TypeOperation.VIEW) {
            ValidateAndFillBeans.disableAllFields(getFiledsPanel());
        }

        //Action apres mise a jour
        afterSetCurrentObject();
    }

    /**
     * Suppression des donnÃ©es du SI
     */
    public void delete() {
        try {
            if (currentObject == null) {
                return;
            }

            boolean status = beforeDelete();

            if (!status) {
                return;
            }

            getManager().delete(getPrimaryKey(currentObject));

            afterDelete();

            if (getParentFrame() != null) {
                getParentFrame().search();
            }

            this.dispose();
        } catch (Exception ex) {
            CustomLogger.loggerWriteError(getClass(), "nouveau()", MessagesBundle.getMessage("new.entity.error"));
        }
    }

    public void quitter() {
        this.dispose();
    }

    /**
     * Panel des opÃ©rations contenant les donnÃ©es de cette fenÃªtre
     *
     * @return
     */
    protected abstract JPanel getFiledsPanel();

    /**
     * Obtention de l'identification de l'entitÃ©
     *
     * @param Object
     * @return
     */
    protected abstract PK getPrimaryKey(T Object);

    /**
     * FenÃªtre principale de l'application
     *
     * @return
     */
    protected abstract JFrame getApplicationFrame();

    /**
     * nom de l'action permettant l'appel de cette fenÃªtre
     *
     * @return
     */
    protected abstract String getActionName();

    /**
     * Bar d'outil dans la fenetre d'edition
     *
     * @return
     */
    //protected abstract JToolBar getToolBar();
    /**
     * Entete de page
     *
     * @return
     */
    protected JPanel getHeaderPanel() {
        return CommonsUtilities.headerPanel();
    }

    protected JPanel getTireHeaderPanel() {
        return CommonsUtilities.titreHeaderPanel();
    }

    /**
     * Pied de page
     *
     * @return
     */
    protected JPanel getFooterPanel() {

        return CommonsUtilities.footerPanel();
    }

    /**
     * Titre de la fÃªnete
     *
     * @return
     */
    protected abstract String getWindowTitle();

    /**
     * Nom de la classe implementant l'interface
     *
     * @return
     */
    public abstract String getWindowClassName();

    /**
     * Icon de la fÃªnetre zone de banniere
     *
     * @return
     */
    protected abstract ImageIcon getImage();

    /**
     * Parametres des raport
     *
     * @return
     */
    protected abstract Map getReportParameters();

    /**
     * Nom du fichier
     *
     * @return
     */
    protected abstract String getJasperFileName();

    /**
     *
     * @param currentObject
     * @return
     */
    protected boolean updatable(T currentObject) {
        return true;
    }

    /**
     *
     * @param currentObject
     * @return
     */
    protected boolean deletable(T currentObject) {
        return true;
    }

    /**
     *
     * @param object
     * @param manager
     * @param typeOperation
     * @param window
     * @return
     */
    //public abstract JInternalFrame getEditInternalFrame(T object , GenericManager manager , TypeOperation typeOperation , JFrame window);
    /**
     * Title of save button
     *
     * @return
     */
    public String getSaveTitle() {
        return MessagesBundle.getMessage("save");
    }

    /**
     *
     * @return
     */
    public String getSaveTooltip() {

        return MessagesBundle.getMessage("save_tooltip");
    }

    /**
     *
     * @return
     */
    public String getCancelTooltip() {

        return MessagesBundle.getMessage("cancel_tooltip");
    }

    /**
     * Icon of save button
     *
     * @return
     */
    public ImageIcon getSaveIcon() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_save.png"));
        return icon;
    }

    public String getCancelTitle() {
        return MessagesBundle.getMessage("cancel");
    }

    public ImageIcon getCancelIcon() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/com/megatim/tools/images/button_cancel.png"));
        return icon;
    }

    /**
     *
     * @return
     */
    protected boolean beforeDelete() {
        return true;
    }

    /**
     *
     * @return
     */
    protected boolean afterDelete() {
        return true;
    }

    /**
     * Actions avant la mise a jour du currrentObject
     *
     * @param currentObject
     * @return
     */
    protected boolean beforeSetCurrentObject() {
        return true;
    }

    /**
     * Actions apres mise a jour du currentObject
     *
     * @return
     */
    protected boolean afterSetCurrentObject() {
        return true;
    }

    /**
     * Verificateur de la prÃ©condition avant sauvegarde
     *
     * @return
     */
    protected boolean beforeSave() {
        return true;
    }

    /**
     * Verification postcondition avant sauvegarde
     *
     * @return
     */
    public boolean afterSave() {
        this.dispose();
        //Succes.getSuccessDialog(PrincipalFrame.principalScreen, true, NotificationType.SUCCES, MessagesBundle.getMessage("save.succes.msg"));
        return true;
    }

    /**
     *
     * @return
     */
    public GenericManager getManager() {
        return manager;
    }

    /**
     *
     * @param manager
     */
    public void setManager(GenericManager manager) {
        this.manager = manager;
    }

    /**
     *
     * @return
     */
    public TypeOperation getTypeOperation() {
        return typeOperation;
    }

    /**
     *
     * @param typeOperation
     */
    public void setTypeOperation(TypeOperation typeOperation) {
        this.typeOperation = typeOperation;
    }

    /**
     *
     * @return
     */
    public AbstractListTemplateFrame getParentFrame() {
        return parentFrame;
    }

    /**
     *
     * @param parentFrame
     */
    public void setParentFrame(AbstractListTemplateFrame parentFrame) {
        this.parentFrame = parentFrame;
    }

    public boolean isInterne() {
        return interne;
    }

    public void setInterne(boolean interne) {
        this.interne = interne;
    }

    public AbstractTableBaseListModel getModel() {
        return model;
    }

    public void setModel(AbstractTableBaseListModel model) {
        this.model = model;
    }

    public AbstractTreeBaseListModel getTreeModel() {
        return treeModel;
    }

    public void setTreeModel(AbstractTreeBaseListModel treeModel) {
        this.treeModel = treeModel;
    }

    public int getSelectedRow() {
        return selectedRow;
    }

    public void setSelectedRow(int selectedRow) {
        this.selectedRow = selectedRow;
    }

    /**
     *
     * @param e
     */
    public void keyReleased(KeyEvent e) {
        //System.out.println("GGGGGGGGGGGGGGGGGGGGG::::::::::::::::::::::::::"+e.getKeyChar()+" ::::::::::: "+e.getSource());
        if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }

    /**
     *
     * @param e
     */
    @SuppressWarnings("empty-statement")
    public void keyPressed(KeyEvent e) {
        //System.out.println("GGGGGGGGGGGGGGGGGGGGG::::::::::::::::::::::::::"+e.getKeyChar()+" ::::::::::: "+e.getSource());
    }

    /**
     *
     * @param e
     */
    @SuppressWarnings("empty-statement")
    public void keyTyped(KeyEvent e) {;
    }

    public void exporter() {

    }

    /**
     *
     * @throws JRException
     */
    public void imprimer(Object data) {

        try {
            String reportFilePath = getJasperFileName();
            // Si le fichier ne se termine pas par .jasper
            if (!reportFilePath.endsWith(".jasper")) {
                reportFilePath = reportFilePath + ".jasper";
            }

            // Creation d'un File sur le fichier
            File reportFile = new File(reportFilePath);

            // Si l'objet n'existe pas
            if (!reportFile.exists()) {
                throw new RuntimeException("gepa.report.helper.buildreport.reportfile.notexist");
            }

            // Si l'objet n'est pas un fichier
            if (!reportFile.isFile()) {
                throw new RuntimeException("gepa.report.helper.buildreport.reportfile.notexist");
            }

            // Chargement du Rapport
            JasperReport report = null;

            // Etat rempli
            JasperPrint jasperPrint = null;

            List values = new ArrayList();
            values.add(data);
            // Chargement du report
            report = (JasperReport) JRLoader.loadObject(reportFile);
            jasperPrint = JasperFillManager.fillReport(report, this.getReportParameters(), new JRBeanCollectionDataSource(values, false));

            // Presentation de l'etat
            this.showReport(jasperPrint);
        } catch (Exception ex) {
            CustomLogger.loggerWriteError(getClass(), "nouveau()", MessagesBundle.getMessage("new.entity.error"));
            Notification.getNotificationDialog(getApplicationFrame(), true, NotificationType.ERROR, "Un erreur est survenu pendant le traitement de votre requête", ex.getMessage());
        }

    }

    /**
     * Methode de presentation d'un etat
     *
     * @param jasperPrint Etat à afficher
     */
    protected void showReport(JasperPrint jasperPrint) throws Exception {

        // Si le fichier jasper est null, arret
        if (jasperPrint == null) {
            return;
        }

        // Creation du viewer
        JRViewer jrViewer = new JRViewer(jasperPrint);

        // Creation de la boite de dilogue
        JDialog dialog = new JDialog(getApplicationFrame());

        // Injection du viewer dans la boite de dialogue
        dialog.getContentPane().add(jrViewer);

        // Gestion de la fermeture de la boite
        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Titre de la boite
        dialog.setTitle("Etat");

        // set modal a true
        dialog.setModal(true);
        // Dimension de la boite
        dialog.setSize(1300, 800);

        //dialog.pack();  
        // Centrage de la boite sur l'IHM
        dialog.setLocationRelativeTo(getApplicationFrame());
        dialog.setVisible(true);

    }
    public ImageIcon getIconePage() {
        ImageIcon icon = CommonsUtilities.getIcone();
        return icon;
    }
}
