/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.megatim.common.clients;


import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author divers
 */
public class Alerte extends javax.swing.JDialog {
    
    private Boolean ifDialogResize = false;
    
    /**
     * 
     * @param parent
     * @param modal
     * @param titreFenetre
     * @param titre
     * @param description 
     */
    public Alerte(JFrame parent, boolean modal, String titreFenetre,String titre, String description) {
        super(parent, modal);
        initComponents();
        this.setTitle(titreFenetre);
        this.titre.setText(titre);
        this.description.setText(description);
        this.resizeDialog();
    }
    
   
    /**
     * 
     * @param parent
     * @param modal
     * @param titreFenetre
     * @param titre
     * @param description 
     */
    public Alerte(JDialog parent, boolean modal, String titreFenetre,String titre, String description) {
        super(parent, modal);
        initComponents();
        this.setTitle(titreFenetre);
        this.titre.setText(titre);
        this.description.setText(description);
        this.resizeDialog();
    }
    
    /**
     * 
     * @param modal
     * @param titreFenetre
     * @param titre
     * @param description 
     */
    public Alerte(boolean modal, String titreFenetre,String titre, String description) {
        super();
        this.setModal(modal);
        initComponents();
        this.setTitle(titreFenetre);
        this.titre.setText(titre);
        this.description.setText(description);
        this.resizeDialog();
    }
    
    /**
     * 
     * @param parent
     * @param titreFenetre
     * @param titre
     * @param description 
     */
    public static void getAlerteDialog(JFrame parent,String titreFenetre,String titre, String description){
        Alerte alerte = new Alerte(parent, true, titreFenetre.toUpperCase(), titre.toUpperCase(), description);
        alerte.setLocationRelativeTo(parent);
        alerte.setVisible(true);
    }
    
    /**
     * 
     * @param parent
     * @param titreFenetre
     * @param titre
     * @param description 
     */
     public static void getAlerteDialog(JDialog parent,String titreFenetre,String titre, String description){
        Alerte alerte = new Alerte(parent, true, titreFenetre.toUpperCase(), titre.toUpperCase(), description);
        alerte.setLocationRelativeTo(parent);
        alerte.setVisible(true);
    }
    /**
     * 
     * @param titreFenetre
     * @param titre
     * @param description 
     */
    public static void getAlerteDialog(String titreFenetre,String titre, String description){
      Alerte alerte = new Alerte(true, titreFenetre.toUpperCase(), titre.toUpperCase(), description);
      alerte.setLocationRelativeTo(null);
      alerte.setVisible(true);
    }
    
    /**
     * Permet de redimensionner la fenetre lors du clic dur le bouton details
     */
    private void resizeDialog(){
        if(!this.ifDialogResize){
            this.setSize(400,175);
        }else{
            this.setSize(400,275);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titre = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        imprimerBtn = new javax.swing.JButton();
        detailsBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alerte");
        setResizable(false);

        titre.setEditable(false);
        titre.setColumns(20);
        titre.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        titre.setRows(5);
        jScrollPane1.setViewportView(titre);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        imprimerBtn.setText("Imprimer");

        detailsBtn.setText("Details");
        detailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(detailsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imprimerBtn)
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimerBtn)
                    .addComponent(detailsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        description.setEditable(false);
        description.setColumns(20);
        description.setRows(5);
        jScrollPane2.setViewportView(description);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsBtnActionPerformed
        // TODO add your handling code here:
        if(this.ifDialogResize){
            this.ifDialogResize = false;
        }else{
            this.ifDialogResize = true;    
        }
        
        this.resizeDialog();
    }//GEN-LAST:event_detailsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JButton detailsBtn;
    private javax.swing.JButton imprimerBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea titre;
    // End of variables declaration//GEN-END:variables
}
