/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.megatim.common.clients;

import java.awt.Frame;
import javax.swing.ImageIcon;

/**
 *
 * @author DEV
 */
public class Confirmation extends javax.swing.JDialog {

    private static Boolean OK_VALUE = false;
    private static Boolean NO_VALUE = false;

    /**
     * Creates new form Confirmation
     */
    public Confirmation(java.awt.Frame parent, boolean modal, NotificationType typenotification, String message, String element) {
        super(parent, modal);
        initComponents();
        buildviews();
        this.message.setText(message + " " + element);
        this.setTitle(typenotification.toString());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tnok = new javax.swing.JToggleButton();
        btno = new javax.swing.JToggleButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 180));

        tnok.setText("OUI");
        tnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnokActionPerformed(evt);
            }
        });

        btno.setText("NON");
        btno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoActionPerformed(evt);
            }
        });

        message.setFont(CommonsUtilities.getFontSimple()); // NOI18N
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Voulez-vous supprimer cet engagement ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 186, Short.MAX_VALUE)
                        .addComponent(tnok, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnokActionPerformed
        // TODO add your handling code here:
        this.OK_VALUE = true;
        NO_VALUE = false;
        this.dispose();
    }//GEN-LAST:event_tnokActionPerformed

    private void btnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoActionPerformed
        // TODO add your handling code here:
        NO_VALUE = false;
        OK_VALUE = false;
        this.dispose();
    }//GEN-LAST:event_btnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btno;
    private javax.swing.JLabel message;
    private javax.swing.JToggleButton tnok;
    // End of variables declaration//GEN-END:variables

    private void buildviews() {
        message.setIcon(new ImageIcon(ClassLoader.getSystemResource("com/megatim/tools/images/warning.png")));
        this.setIconImage((new ImageIcon(ClassLoader.getSystemResource("com/megatim/tools/images/warning.png"))).getImage());
    }

    public static boolean getConfirmationDialog(Frame parent, boolean modal, NotificationType typenotification, String message, String element) {
        Confirmation confirmation = new Confirmation(parent, true, typenotification, message, element);
        confirmation.setModal(modal);
        confirmation.setLocationRelativeTo(parent);
        confirmation.setVisible(true);
        if (OK_VALUE) {
            return OK_VALUE;
        } else {
            return NO_VALUE;
        }
    }
}
