/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.megatim.security.clients;

import com.bekosoftware.genericmanagerlayer.core.ifaces.GenericManager;
import com.megatim.common.clients.BannierePanel;
import com.megatim.common.clients.CommonsUtilities;
import com.megatim.common.clients.Messages;
import com.megatim.common.clients.NotificationType;
import com.megatim.common.services.IocContext;
import com.megatim.common.utilities.CustomHTTPClient;
import com.megatim.security.callbackhandler.AuthentificationCallBackHandler;
import com.megatim.security.ifaces.client.ClientInterfaceSecurity;
import com.megatim.security.manager.connection.ManagerConnection;
import com.megatim.security.model.Profil;
import com.megatim.security.model.Utilisateur;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author divers
 */
public class Authentification extends javax.swing.JFrame {

    private IocContext ctx;
    private GenericManager manager;
    private ClientInterfaceSecurity client;
    private static boolean statusExerciceBudgetaire = true;
    private  ImageIcon icon =new ImageIcon(getClass().getResource("/com/megatim/tools/images/icone.png"));

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        this.ctx = new IocContext();
        //chargerDataBaseTest();
        initComponents();
        getBanniere();
        chargerAnneeBudgetaire();
    }

    /**
     * Creates new form Authentification
     */
    public Authentification(ClientInterfaceSecurity client) {
        this.ctx = new IocContext();
        this.client = client;
        //chargerDataBaseTest();
        initComponents();
        getBanniere();
        chargerAnneeBudgetaire();
    }

    
    /**
     * Creates new form Authentification sans exercice budgetaire
     */
    public Authentification(ClientInterfaceSecurity client, boolean value , ImageIcon icone) {
        this.ctx = new IocContext();
        this.client = client;
        statusExerciceBudgetaire=value;
        this.icon=icone;
        initComponents();
        getBanniere();

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBanniere = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cbAnneeBudgetaire = new javax.swing.JComboBox();
        btnConnexion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        ImageIcon icon = this.client.getIconWindow();
        this.setIconImage(icon.getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jPanelBanniereLayout = new javax.swing.GroupLayout(jPanelBanniere);
        jPanelBanniere.setLayout(jPanelBanniereLayout);
        jPanelBanniereLayout.setHorizontalGroup(
            jPanelBanniereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        jPanelBanniereLayout.setVerticalGroup(
            jPanelBanniereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        labelLogin.setText("Login");

    	if(statusExerciceBudgetaire){
    		builpanelConnexionDefualt();
    	}else{
    		builpanelConnexionSimple(getIcon());
    	}
      
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void builpanelConnexionSimple(ImageIcon icone){
  	  jPanelBanniere = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      labelLogin = new javax.swing.JLabel();
      login = new javax.swing.JTextField();
      labelPassword = new javax.swing.JLabel();
      Password = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      cbAnneeBudgetaire = new javax.swing.JComboBox();
      btnConnexion = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);
      this.setIconImage(this.icon.getImage());
      addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent evt) {
              formWindowClosing(evt);
          }
      });

      javax.swing.GroupLayout jPanelBanniereLayout = new javax.swing.GroupLayout(jPanelBanniere);
      jPanelBanniere.setLayout(jPanelBanniereLayout);
      jPanelBanniereLayout.setHorizontalGroup(
          jPanelBanniereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGap(0, 359, Short.MAX_VALUE)
      );
      jPanelBanniereLayout.setVerticalGroup(
          jPanelBanniereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGap(0, 52, Short.MAX_VALUE)
      );

      labelLogin.setText("Login");
		
		login.addKeyListener(new java.awt.event.KeyAdapter() {
          public void keyReleased(java.awt.event.KeyEvent evt) {
              loginKeyReleased(evt);
          }
      });

      labelPassword.setText("Password");
		
		Password.addKeyListener(new java.awt.event.KeyAdapter() {
          public void keyReleased(java.awt.event.KeyEvent evt) {
              passwordKeyReleased(evt);
          }
      });

      jLabel1.setText("Exercice Budgetaire");

      cbAnneeBudgetaire.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
              .addGap(35, 35, 35)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(labelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                  .addComponent(jLabel1))
              .addGap(18, 18, 18)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(cbAnneeBudgetaire, 0, 184, Short.MAX_VALUE)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                      .addComponent(Password)))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
              .addContainerGap()
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(labelPassword)
                  .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel1)
                  .addComponent(cbAnneeBudgetaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      btnConnexion.setText("Se connecter");
      btnConnexion.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              btnConnexionActionPerformed(evt);
          }
      });

      jButton1.setText("Annuler");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jButton1ActionPerformed(evt);
          }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanelBanniere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnConnexion)
              .addGap(17, 17, 17)
              .addComponent(jButton1)
              .addGap(72, 72, 72))
      );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
              .addComponent(jPanelBanniere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(17, 17, 17)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnConnexion)
                  .addComponent(jButton1))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      
      cbAnneeBudgetaire.setVisible(this.statusExerciceBudgetaire);
      jLabel1.setVisible(this.statusExerciceBudgetaire);
    }
    
 public void builpanelConnexionDefualt(){
	  jPanelBanniere = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      labelLogin = new javax.swing.JLabel();
      login = new javax.swing.JTextField();
      labelPassword = new javax.swing.JLabel();
      Password = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      cbAnneeBudgetaire = new javax.swing.JComboBox();
      btnConnexion = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);
      this.setIconImage(this.icon.getImage());
      addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent evt) {
              formWindowClosing(evt);
          }
      });

      javax.swing.GroupLayout jPanelBanniereLayout = new javax.swing.GroupLayout(jPanelBanniere);
      jPanelBanniere.setLayout(jPanelBanniereLayout);
      jPanelBanniereLayout.setHorizontalGroup(
          jPanelBanniereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGap(0, 359, Short.MAX_VALUE)
      );
      jPanelBanniereLayout.setVerticalGroup(
          jPanelBanniereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGap(0, 52, Short.MAX_VALUE)
      );

      labelLogin.setText("Login");
		
		login.addKeyListener(new java.awt.event.KeyAdapter() {
          public void keyReleased(java.awt.event.KeyEvent evt) {
              loginKeyReleased(evt);
          }
      });

      labelPassword.setText("Password");
		
		Password.addKeyListener(new java.awt.event.KeyAdapter() {
          public void keyReleased(java.awt.event.KeyEvent evt) {
              passwordKeyReleased(evt);
          }
      });

      jLabel1.setText("Exercice Budgetaire");

      cbAnneeBudgetaire.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
              .addGap(35, 35, 35)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(labelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                  .addComponent(jLabel1))
              .addGap(18, 18, 18)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(cbAnneeBudgetaire, 0, 184, Short.MAX_VALUE)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                      .addComponent(Password)))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
              .addContainerGap()
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(labelPassword)
                  .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel1)
                  .addComponent(cbAnneeBudgetaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      btnConnexion.setText("Se connecter");
      btnConnexion.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              btnConnexionActionPerformed(evt);
          }
      });

      jButton1.setText("Annuler");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jButton1ActionPerformed(evt);
          }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanelBanniere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnConnexion)
              .addGap(17, 17, 17)
              .addComponent(jButton1)
              .addGap(72, 72, 72))
      );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
              .addComponent(jPanelBanniere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(17, 17, 17)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnConnexion)
                  .addComponent(jButton1))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      
      cbAnneeBudgetaire.setVisible(this.statusExerciceBudgetaire);
      jLabel1.setVisible(this.statusExerciceBudgetaire);
    	
    }
	
	private void chargerAnneeBudgetaire(){
        
        Vector listeAnneesBugetaires = loadListAnneeBudgetaires();
        
        if(!listeAnneesBugetaires.isEmpty()){
        
            //On set le modele
            this.cbAnneeBudgetaire.setModel(new DefaultComboBoxModel(loadListAnneeBudgetaires()));
        }else{
            
            //On cache le label
            this.jLabel1.setVisible(false);
            
            //On cache le combobox
            this.cbAnneeBudgetaire.setVisible(false);
            
            //On ajuste la taille de la fenetre
            this.setPreferredSize(new Dimension(this.getPreferredSize().width,220));
            
            //On redessine
            pack();
        }
    }
	
    private GenericManager loadManager(String nameClasseQualified) {
        try {
            manager = (GenericManager) ctx.lookup(nameClasseQualified);
        } catch (Exception ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }

        return manager;
    }

    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexionActionPerformed
        // TODO add your handling code here:*
    	authentication();

    }//GEN-LAST:event_btnConnexionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginKeyReleased(java.awt.event.KeyEvent evt) {

        //Test si la touche appuyée est la touche Entree
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        	authentication();
        }
    }

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {

        //Test si la touche appuyée est la touche Entree
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        	authentication();
        }
    }

    private Vector loadListAnneeBudgetaires() {
        GenericManager exerciceBudgetaireManager = this.client.getExerciceBudgetaireManager();
        Vector myVector = new Vector();
        
        //On teste si le manager est different de null
        if(exerciceBudgetaireManager != null){
        
            List datas = exerciceBudgetaireManager.findAll();

            for (Object data : datas) {
                myVector.add(data);
            }
             Comparator comparator = Collections.reverseOrder();
            Collections.sort(myVector, comparator) ;
        }
        return myVector;
    }

    private void chargerDataBaseTest() {
        /*Autorisation a1 = new Autorisation();
         Autorisation a2 = new Autorisation();
         Autorisation a3 = new Autorisation();
         Autorisation a4 = new Autorisation();
         Autorisation a5 = new Autorisation();
       
         a1.setId(1L);
         a1.setDescription("ENGAMENT1");
         a1.setNomAutorisation("ENGAMENT1");
         a1.setStatut("WRITE");
        
         a2.setId(2L);
         a2.setDescription("ENGAMENT2");
         a2.setNomAutorisation("ENGAMENT2");
         a2.setStatut("WRITE");
        
         a3.setId(3L);
         a3.setDescription("ENGAMENT3");
         a3.setNomAutorisation("ENGAMENT3");
         a3.setStatut("WRITE");
        
         a4.setId(4L);
         a4.setDescription("ENGAMENT4");
         a4.setNomAutorisation("ENGAMENT4");
         a4.setStatut("WRITE");
        
         a5.setId(5L);
         a5.setDescription("ENGAMENT5");
         a5.setNomAutorisation("ENGAMENT5");
         a5.setStatut("WRITE");*/

        ArrayList liste = new ArrayList();
        /*liste.add(a1);
         liste.add(a2);
         liste.add(a3);
         liste.add(a4);
         liste.add(a5);*/

        Profil profil = new Profil();
        profil.setNom("ADMINISTRATEUR");
        profil.setDescription("ADMINISTRATEUR");
        profil.setAutorisations(liste);

        this.manager = this.loadManager("com.megatim.security.core.impl.Profil.ProfilManagerImpl");
        this.manager.save(profil);

        Utilisateur user = new Utilisateur();
        user.setLogin("admin");
        user.setNom("admin");
        user.setPassword("admin");
        user.setPrenom("admin");
        user.setProfil(profil);

        this.manager = this.loadManager("com.megatim.security.core.impl.Utilisateur.UtilisateurManagerImpl");
        this.manager.save(user);
    }

    public void connexion() {
        
        //Si on se logge depuis de client
        if(!this.client.ifLoginByServer()){
            
            if (ManagerConnection.login("WithoutEncrypt", new AuthentificationCallBackHandler(this), System.getProperty("user.dir") + File.separator + "com"+File.separator+"megatim"+File.separator+"security"+File.separator+"loginmodule"+File.separator+"config"+File.separator+"jass_loginModule.config")) {
                this.dispose();
				
                if(statusExerciceBudgetaire){
					this.client.launchClientFrame(ManagerConnection.currentUser, this.cbAnneeBudgetaire.getSelectedItem());
				}else{
					this.client.launchClientFrame(ManagerConnection.currentUser, null);
				}
            } else {
                Messages.Messages(this, true, NotificationType.ERROR, "Paramètres de connexion incorrects", "ECHEC OPERATION", "");
            }
        }else{
            
            if(CustomHTTPClient.ifLoginHTTPClient(this.client.getUrlServerForAuthentification(),this.login.getText(),this.Password.getText())){
                this.dispose();
                this.client.launchClientFrame(this.login.getText(), this.Password.getText());
            }
        }
    }

    
    public void connexionSimple() {
    	Utilisateur user = new Utilisateur();
    	user.setLogin(login.getText());
    	user.setPassword(Password.getText());
        if (ManagerConnection.authenticateUser(user)) {
            this.dispose();
            this.client.launchClientFrame(ManagerConnection.currentUser, null);
        } else {
            Messages.Messages(this, true, NotificationType.ERROR, "Paramètres de connexion incorrects", "ECHEC OPERATION", "");
        }

        // penser a afficher les menu en fontion de l'état de l'exercice budgetaire
        //A supprimer
        //this.dispose();
        //this.client.launchClientFrame(new UserPrincipal("login",new Utilisateur()),this.cbAnneeBudgetaire.getSelectedItem());
    }
    public void getBanniere() {
        JLabel lblIcon = new javax.swing.JLabel();
        JLabel lblTitle = new javax.swing.JLabel();
        //Intitialisation logo
        //this.setIconImage(CommonsUtilities.getIcon());
        this.setTitle(getTitle());
        //traitement du panel Header
        this.jPanelBanniere.setLayout(new BorderLayout());

        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("com/megatim/tools/images/BtitreNew.png"));

        JPanel entetePanel = new BannierePanel(icon.getImage());
        lblIcon.setIcon(getImage());
        entetePanel.add(lblIcon);
        lblTitle.setFont(CommonsUtilities.getFontTitreFrame());
        lblTitle.setForeground(CommonsUtilities.COULEUR_TITRE_FRAME);
        lblTitle.setText("AUTHENTIFICATION");
        lblTitle.setName("lblTitle"); // NOI18N
        entetePanel.add(lblTitle);
        this.jPanelBanniere.add(entetePanel, BorderLayout.CENTER);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                Authentification authentification = new Authentification();
                authentification.setLocationRelativeTo(authentification.getParent());
                authentification.setVisible(true);

            }
        });
    }

    public JPasswordField getPassword() {
        return Password;
    }

    public void setPassword(JPasswordField Password) {
        this.Password = Password;
    }

    public JTextField getLogin() {
        return login;
    }

    public void setLogin(JTextField login) {
        this.login = login;
    }

    /**
     * Methode permettant de retourner l'icone de la fenetre
     *
     * @return javax.swing.ImageIcon
     */
    public ImageIcon getImage() {
        try {
            ImageIcon icon = null;
            icon = CommonsUtilities.getImageLogin();
            return icon;
        } catch (Exception ex) {;
        }
        return null;
    }
    
    /**
	 * @return the icon
	 */
	public ImageIcon getIcon() {
		return icon;
	}

	/**
	 * @param icon the icon to set
	 */
	public void setIcon(ImageIcon icon) {
		this.icon = icon;
	}

	public boolean statusExerciceBudgetaire(){
    	return statusExerciceBudgetaire;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btnConnexion;
    private javax.swing.JComboBox cbAnneeBudgetaire;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBanniere;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelespase;
    private javax.swing.JTextField login;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the statusExerciceBudgetaire
	 */
	public boolean isStatusExerciceBudgetaire() {
		return statusExerciceBudgetaire;
	}

	/**
	 * @param statusExerciceBudgetaire the statusExerciceBudgetaire to set
	 */
	public void setStatusExerciceBudgetaire(boolean statusExerciceBudgetaire) {
		this.statusExerciceBudgetaire = statusExerciceBudgetaire;
	}
	
	public void authentication(){
		   // TODO add your handling code here:*
            if(statusExerciceBudgetaire){
                connexion();
            }else{
                connexionSimple();
            }
	}
}
