//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.17 at 08:11:24 AM GMT+01:00 
//


package net.keren.keren;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.keren.net/keren}action"/>
 *         &lt;element ref="{http://www.keren.net/keren}menu" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.keren.net/keren}menuitem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.keren.net/keren}formRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.keren.net/keren}treeRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.keren.net/keren}reportRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.keren.net/keren}dashboardRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.keren.net/keren}calendarRecord" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "action",
    "menu",
    "menuitem",
    "formRecord",
    "treeRecord",
    "reportRecord",
    "dashboardRecord",
    "calendarRecord"
})
@XmlRootElement(name = "keren")
public class Keren {

    @XmlElement(required = true)
    protected Action action;
    protected List<Menu> menu;
    protected List<Menuitem> menuitem;
    protected List<FormRecord> formRecord;
    protected List<TreeRecord> treeRecord;
    protected List<ReportRecord> reportRecord;
    protected List<DashboardRecord> dashboardRecord;
    protected List<CalendarRecord> calendarRecord;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setAction(Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the menu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Menu }
     * 
     * 
     */
    public List<Menu> getMenu() {
        if (menu == null) {
            menu = new ArrayList<Menu>();
        }
        return this.menu;
    }

    /**
     * Gets the value of the menuitem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menuitem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenuitem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Menuitem }
     * 
     * 
     */
    public List<Menuitem> getMenuitem() {
        if (menuitem == null) {
            menuitem = new ArrayList<Menuitem>();
        }
        return this.menuitem;
    }

    /**
     * Gets the value of the formRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormRecord }
     * 
     * 
     */
    public List<FormRecord> getFormRecord() {
        if (formRecord == null) {
            formRecord = new ArrayList<FormRecord>();
        }
        return this.formRecord;
    }

    /**
     * Gets the value of the treeRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the treeRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTreeRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TreeRecord }
     * 
     * 
     */
    public List<TreeRecord> getTreeRecord() {
        if (treeRecord == null) {
            treeRecord = new ArrayList<TreeRecord>();
        }
        return this.treeRecord;
    }

    /**
     * Gets the value of the reportRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportRecord }
     * 
     * 
     */
    public List<ReportRecord> getReportRecord() {
        if (reportRecord == null) {
            reportRecord = new ArrayList<ReportRecord>();
        }
        return this.reportRecord;
    }

    /**
     * Gets the value of the dashboardRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dashboardRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDashboardRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DashboardRecord }
     * 
     * 
     */
    public List<DashboardRecord> getDashboardRecord() {
        if (dashboardRecord == null) {
            dashboardRecord = new ArrayList<DashboardRecord>();
        }
        return this.dashboardRecord;
    }

    /**
     * Gets the value of the calendarRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calendarRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalendarRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CalendarRecord }
     * 
     * 
     */
    public List<CalendarRecord> getCalendarRecord() {
        if (calendarRecord == null) {
            calendarRecord = new ArrayList<CalendarRecord>();
        }
        return this.calendarRecord;
    }

}
