//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.17 at 08:11:24 AM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.keren.net/keren", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.keren.keren;
